---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics", "/stats/prometheus"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: envoy-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: envoy-prometheus
  namespace: projectcontour
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-prometheus
spec:
  selector:
    prometheus: envoy-prometheus
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: envoy-prometheus
spec:
  scrapeInterval: "5s"
  serviceAccountName: envoy-prometheus
  serviceMonitorSelector:
    matchLabels:
      app: envoy
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  selector:
    matchLabels:
      app: envoy
  namespaceSelector:
    matchNames:
    - projectcontour
  endpoints:
    - targetPort: 8002
      interval: 30s
      path: /stats/prometheus
