apiVersion: apps/v1
kind: Deployment
metadata:
  name: particles-v1.0.2
  namespace: production
  labels:
    app: particles
    version: 1.0.2
spec:
  selector:
    matchLabels:
      app: particles
      version: 1.0.2
  replicas: 2
  template:
    metadata:
      labels:
        app: particles
        version: 1.0.2
    spec:
      containers:
      - name: particles
        image: magneticio/particles:1.4.22
        imagePullPolicy: Always
        args:
          - "--color=#FF0000"
          - "--appVersion=v1.0.2"
          - "--showStats"
          - "--clusterCount=50"
          - "--particlesPerCluster=10"
          - "--minMem=300"
          - "--healthCheckGracePeriodSeconds=125"
          - "--resourceCheckGracePeriodSeconds=60"
        env:
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: particles
              divisor: 1Mi
              resource: limits.memory
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            cpu: "0.826"
            memory: "303.321Mi"
          requests:
            cpu: "0.395"
            memory: "105.497Mi"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: autoscaler-particles-v1.0.2
  namespace: production
spec:
  template:
    metadata:
      name: autoscaler-particles-v1.0.2
    spec:
      containers:
      - name: autoscaler
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_NAME
          value: particles-v1.0.2
        - name: DEPLOYMENT_LABELS
          value: app=particles,version=1.0.2
        - name: MIN_REPLICAS
          value: "2"
        - name: MAX_REPLICAS
          value: "4"
        image: magneticio/particles-autoscaler:0.1.23
      restartPolicy: OnFailure
      serviceAccountName: demo-autoscaler
