apiVersion: apps/v1
kind: Deployment
metadata:
  name: particles-v1.1.1
  labels:
    app: particles
    version: 1.1.1
spec:
  selector:
    matchLabels:
      app: particles
      version: 1.1.1
  replicas: 1
  template:
    metadata:
      labels:
        app: particles
        version: 1.1.1
    spec:
      containers:
      - name: particles
        image: magneticio/particles
        imagePullPolicy: Always
        args:
          - "--appVersion=v1.1.1"
          - "--color=#0000FF"
          - "--shape=rectangle"
          - "--showStats"
          - "--clusterCount=50"
          - "--particlesPerCluster=10"
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: 0.1
            memory: 256
